services:
- type: web
  name: zero
  env: docker
  disk:
    name: datadir
    mountPath: /dgraph
  dockerCommand: dgraph zero

- type: web
  name: alpha
  env: docker
  disk:
    name: datadir
    mountPath: /dgraph
  envVars:
    - key: ZERO
      fromService:
        name: zero
        type: web
        envVarKey: hostport
  dockerCommand: dgraph alpha --lru_mb=2048 --zero=${ZERO}

- type: web
  name: ratel
  env: docker 
  dockerCommand: dgraph-ratel