services:
- type: pserv
  name: zero
  env: docker
  disk:
    name: datadir
    mountPath: /dgraph
  startCommand: dgraph zero --my=zero:${ZERO_PORT}

- type: pserv
  name: alpha
  env: docker
  disk:
    name: datadir
    mountPath: /dgraph
  envVars:
    - key: ZERO_PORT
      fromService:
        name: zero
        type: pserv
        property: port
    - key: ALPHA_PORT
      fromService:
        name: zero
        type: pserv
        property: port
  startCommand: dgraph alpha --my=alpha:${ALPHA_PORT} --lru_mb=2048 --zero=zero:${ZERO_PORT}

- type: web
  name: ratel
  env: docker 
  startCommand: dgraph-ratel

envVarGroups:
  - name: ports
    envVars:
    - key: ALPHA_PORT
      value: 7080
    - key: ZERO_PORT
      value: 5080